services:
    dante:
        image: adegtyarev/dante
        command: sockd-username
        restaart: always
        environment:
            SOCKD_USER_NAME: $SOCKD_USER_NAME
            SOCKD_USER_PASSWORD: $SOCKD_USER_PASSWORD
        ports:
            - $SOCKD_PORT:1080
        volumes:
            - ./sockd.conf:/etc/sockd.conf
